version: '3.1'
services:
  db:
    image: postgres:14.5-alpine
    container_name: postgresJetup
    ports:
      - 5090:5432
    volumes:
      - jetup:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_task_jetup
    restart: always
  app:
    build: .
    command: npm run start
    ports:
      - 5000:5000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
volumes:
  jetup:
